# Generated by Django 3.2.23 on 2026-02-24 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20240911_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='discovered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='techs',
            field=models.ManyToManyField(blank=True, related_name='techs', to='startScan.Technology'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='start_scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='discovered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='subscan',
            name='start_scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='discovered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
