# Generated by Django 3.2.23 on 2026-02-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_auto_20260224_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
