# Generated by Django 3.2.23 on 2026-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_humint_sigint_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_proxy_mode',
            field=models.CharField(choices=[('auto', 'Auto (use proxy if available)'), ('none', 'No proxy (direct connection)')], default='auto', help_text='Whether to route scan traffic through a proxy.', max_length=20),
        ),
    ]
