# Generated by Django 3.2.23 on 2026-04-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startScan', '0008_low_ipaddress_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='created_at',
            field=models.DateTimeField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='scanactivity',
            name='created_at',
            field=models.DateTimeField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='scanactivity',
            name='scan_history',
            field=models.ForeignKey(blank=True, db_column='scan_of_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
