# Generated by Django 3.2.23 on 2026-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
