# Generated by Django 3.2.23 on 2026-02-24 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
