# Generated by Django 3.2.23 on 2026-02-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20260224_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='targetApp.domainregistration'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrant', to='targetApp.domainregistration'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='targetApp.registrar'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech', to='targetApp.domainregistration'),
        ),
    ]
