# Generated by Django 3.2.23 on 2026-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_auto_20260226_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='historical_ips',
            field=models.ManyToManyField(blank=True, related_name='domain_historical_ips', to='targetApp.HistoricalIP'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='domains',
            field=models.ManyToManyField(related_name='organizations', to='targetApp.Domain'),
        ),
    ]
